### ISSUE TITLE
Cannot load JS SDK with RequireJS

### ISSUE THREAD

**Issue by o-nix** [playlyfe/playlyfe-js-sdk#3]
Hi!
When I do `require([])` on the file, it constantly returns `Socket` prototype instead of `Playlyfe` one.
Managed to do it by splitting `eio` and `playlyfe` into separate files. But I think that's not a solution.

**Comment by pyros2097** [comment]
Maybe its because of the new operator, try removing that it might work... 
```
return new Playlyfe($, eio);
```

**Comment by o-nix** [comment]
No no no, I inspected the instance I get in the require callback, it is `Socket`.
