### ISSUE TITLE
Promisify client.api() calls

### ISSUE THREAD

**Issue by o-nix** [playlyfe/playlyfe-js-sdk#4]
Probably by just removing this statement

```
throw Error('Invalid callback provided, please provide a function')
```

because

```
$.ajax(ajaxOptions);
```

already returns a jQuery _deferred_ object.

**Comment by o-nix** [comment]
+ extract `_method = args[1]` check/set due to `if (args.length >= 3)`

**Comment by pyros2097** [comment]
I'm planning a rewrite of the js sdk to make just like the other sdk's, fully promisified and simpler to use but yeah this might be a simpler way

**Comment by o-nix** [comment]
:+1:
